feat: [정혜연] 자기소개서 작성 완료
kakaotrack/opensource-class pull request #521
Opened 2022-04-22 14:58 UTC by HY219

2022-04-27 09:18 UTC, violetblue requested changes
PR에 정혜연 학생 자기 소개 외에 다른 파일이 포함되어 있어요

2022-04-27 09:25 UTC, violetblue commented on github-2022/2019105041_정혜연.md
> +&nbsp; GitHub Pages 링크: : https://strong-alpaca-ac0e04.netlify.app/
github page가 아니라 netlify를 사용한 이유가 있을까요?

2022-04-28 10:31 UTC, HY219 commented on github-2022/2019105041_정혜연.md
> +&nbsp; GitHub Pages 링크: : https://strong-alpaca-ac0e04.netlify.app/
github page로는 배포해본 경험이 있어, 다른 서비스를 통해 배포해보고 싶었습니다!

2022-04-28 12:00 UTC, HY219 commented
> PR에 정혜연 학생 자기 소개 외에 다른 파일이 포함되어 있어요
포함된 파일 제거 했습니다!

2022-04-29 04:42 UTC, merged