정진아 자기소개서
kakaotrack/opensource-class pull request #528
Opened 2023-03-31 04:31 UTC by SpaceDust75

컴퓨터공학전공 2021108272 정진아
자기소개서 임시 생성

2023-04-06 09:11 UTC, violetblue requested changes
자기소개 내용이 좋네요 ^^
fork 저장소는 2개 이상이고, 설명도 추가해야 합니다. (과제 다시 확인!)

2023-04-06 10:13 UTC, SpaceDust75 commented
<!--
/* Font Definitions */
@font-face
	{font-family:Gulim;
	panose-1:2 11 6 0 0 1 1 1 1 1;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:"Malgun Gothic";
	panose-1:2 11 5 3 2 0 0 2 0 4;}
@font-face
	{font-family:"Malgun Gothic";}
@font-face
	{font-family:Gulim;
	panose-1:2 11 6 0 0 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	text-align:justify;
	text-justify:inter-ideograph;
	text-autospace:none;
	word-break:break-hangul;
	font-size:10.0pt;
	font-family:"맑은 고딕",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
/* Page Definitions */
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:3.0cm 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->교수님 실수로 push와 커밋하는 과정에서 잘못하여 작성한 코드가 날라갔습니다. 혹시 해결 방법이 있을까요?  Windows용 메일에서 발송된 메일입니다. 보낸 사람: violetblue보낸 날짜: 2023년 4월 6일 목요일 오후 6:11받는 사람: kakaotrack/opensource-class참조: SpaceDust75; Author제목: Re: [kakaotrack/opensource-class] 정진아 자기소개서 (PR ***@***.*** requested changes on this pull request.자기소개 내용이 좋네요 ^^fork 저장소는 2개 이상이고, 설명도 추가해야 합니다. (과제 다시 확인!)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2023-04-06 10:18 UTC, SpaceDust75 commented
> 자기소개 내용이 좋네요 ^^ fork 저장소는 2개 이상이고, 설명도 추가해야 합니다. (과제 다시 확인!)

혹시 실수로 github에서 작성한 내용은 local로 불러오려다가 반대로 push를 해서 파일이 사라졌는데 복구가 가능할까요?

2023-04-06 10:48 UTC, SpaceDust75 commented
<!--
/* Font Definitions */
@font-face
	{font-family:Gulim;
	panose-1:2 11 6 0 0 1 1 1 1 1;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:"Malgun Gothic";
	panose-1:2 11 5 3 2 0 0 2 0 4;}
@font-face
	{font-family:"Malgun Gothic";}
@font-face
	{font-family:Gulim;
	panose-1:2 11 6 0 0 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	text-align:justify;
	text-justify:inter-ideograph;
	text-autospace:none;
	word-break:break-hangul;
	font-size:10.0pt;
	font-family:"맑은 고딕",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
/* Page Definitions */
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:3.0cm 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->오늘 자정 전에 파일 다시 만들어서 올리겠습니다.죄송합니다 교수님 Windows용 메일에서 발송된 메일입니다. 보낸 사람: violetblue보낸 날짜: 2023년 4월 6일 목요일 오후 6:11받는 사람: kakaotrack/opensource-class참조: SpaceDust75; Author제목: Re: [kakaotrack/opensource-class] 정진아 자기소개서 (PR ***@***.*** requested changes on this pull request.자기소개 내용이 좋네요 ^^fork 저장소는 2개 이상이고, 설명도 추가해야 합니다. (과제 다시 확인!)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2023-04-06 12:41 UTC, SpaceDust75 commented
> 자기소개 내용이 좋네요 ^^ fork 저장소는 2개 이상이고, 설명도 추가해야 합니다. (과제 다시 확인!)

교수님 수정 완료하였습니다. 확인 부탁드려요.

2023-04-07 01:01 UTC, violetblue approved these changes

2023-04-07 01:02 UTC, merged